# Generated by Django 5.0.4 on 2024-10-17 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dtb", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="predictor",
            name="api_key",
            field=models.CharField(max_length=255, verbose_name="OpenAI API Key"),
        ),
    ]
