# Generated by Django 5.0.4 on 2024-05-06 03:49

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dtb", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="auto_response",
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name="Predictor",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "api_key",
                    models.CharField(max_length=100, verbose_name="OpenAI API Key"),
                ),
                ("context", models.TextField(verbose_name="System Prompt")),
                (
                    "bot",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="predictor",
                        to="dtb.bot",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
