# Generated by Django 5.0.4 on 2024-05-06 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dtb", "0002_chat_auto_response_predictor"),
    ]

    operations = [
        migrations.AddField(
            model_name="bot",
            name="auto_response",
            field=models.BooleanField(default=False),
        ),
    ]
